'use strict';

const commonGlobals = {
  __dirname: 'readonly',
  Buffer: 'readonly',
  clearTimeout: 'readonly',
  console: 'readonly',
  global: 'readonly',
  module: 'readonly',
  process: 'readonly',
  require: 'readonly',
  setInterval: 'readonly',
  setTimeout: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
};

const jestGlobals = {
  afterAll: 'readonly',
  afterEach: 'readonly',
  beforeAll: 'readonly',
  beforeEach: 'readonly',
  describe: 'readonly',
  expect: 'readonly',
  jest: 'readonly',
  test: 'readonly',
};

const browserGlobals = {
  document: 'readonly',
  fetch: 'readonly',
  localStorage: 'readonly',
  navigator: 'readonly',
  window: 'readonly',
};

const serviceWorkerGlobals = {
  caches: 'readonly',
  fetch: 'readonly',
  self: 'readonly',
};

const publicRules = {
  'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
  'no-console': 'off',
  eqeqeq: 'error',
  curly: 'error',
  semi: ['error', 'always'],
  quotes: ['error', 'single', { avoidEscape: true }],
  indent: ['error', 2],
  'max-len': ['warn', { code: 120 }],
  'no-eval': 'error',
  'no-implied-eval': 'error',
  'no-new-func': 'error',
  'no-throw-literal': 'error',
  'prefer-promise-reject-errors': 'error',
};

module.exports = [
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...commonGlobals,
      },
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      eqeqeq: 'error',
      curly: 'error',
      semi: ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      indent: ['error', 2],
      'max-len': ['warn', { code: 120 }],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-return-await': 'error',
      'no-throw-literal': 'error',
      'prefer-promise-reject-errors': 'error',
      'require-await': 'warn',
      'no-param-reassign': ['warn', { props: false }],
      'no-shadow': 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'no-fallthrough': 'error',
      'no-duplicate-imports': 'error',
      'no-useless-constructor': 'error',
      'prefer-template': 'warn',
      'no-loop-func': 'error',
      'no-await-in-loop': 'warn',
      'array-callback-return': 'error',
      'no-constructor-return': 'error',
    },
  },
  {
    files: ['public/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...commonGlobals,
        ...browserGlobals,
      },
    },
    rules: publicRules,
  },
  {
    files: ['public/sw.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...commonGlobals,
        ...serviceWorkerGlobals,
      },
    },
    rules: publicRules,
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...commonGlobals,
        ...jestGlobals,
      },
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      eqeqeq: 'error',
      curly: 'error',
      semi: ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      indent: ['error', 2],
      'max-len': ['warn', { code: 120 }],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-return-await': 'error',
      'no-throw-literal': 'error',
      'prefer-promise-reject-errors': 'error',
      'require-await': 'warn',
      'no-param-reassign': ['warn', { props: false }],
      'no-shadow': 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'no-fallthrough': 'error',
      'no-duplicate-imports': 'error',
      'no-useless-constructor': 'error',
      'prefer-template': 'warn',
      'no-loop-func': 'error',
      'no-await-in-loop': 'warn',
      'array-callback-return': 'error',
      'no-constructor-return': 'error',
    },
  },
  {
    files: ['eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...commonGlobals,
      },
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-console': 'off',
      eqeqeq: 'error',
      curly: 'error',
      semi: ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      indent: ['error', 2],
      'max-len': ['warn', { code: 120 }],
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-return-await': 'error',
      'no-throw-literal': 'error',
      'prefer-promise-reject-errors': 'error',
      'require-await': 'warn',
      'no-param-reassign': ['warn', { props: false }],
      'no-shadow': 'warn',
      'consistent-return': 'warn',
      'default-case': 'warn',
      'no-fallthrough': 'error',
      'no-duplicate-imports': 'error',
      'no-useless-constructor': 'error',
      'prefer-template': 'warn',
      'no-loop-func': 'error',
      'no-await-in-loop': 'warn',
      'array-callback-return': 'error',
      'no-constructor-return': 'error',
    },
  },
];
